### ISSUE TITLE
Nettoyer les noms de fichiers dans le rapport

### ISSUE THREAD

**Issue by frisch-raphael** [frisch-raphael/Serpico#7]
Modifier le fonctionnement de Serpico pour que dans le rapport un caractère spécial soit utilisé pour encadrer les impressions d'écran, que les balises entre ces caractères spéciaux soient nettoyées, et que si l'impression d'écran n'existe pas il n'apparaisse pas de saut de ligne

**Comment by 4B3l0** [comment]
Pour faire cela proprement, il faudra définir un caractère spécifique a l'insertion de screenshot plutôt que [!! et !!]

**Comment by 4B3l0** [comment]
Le remplacement dans le template est fait, reste a gerer le cas ou l'image est absente
